server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled:
        force: true

spring:
  application:
    name: openapi
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLCDB
    username: sys as sysdba
    password: myorapwd1
    driver-class-name: oracle.jdbc.OracleDriver


openapi:
  datagokr:
    serviceKey: ibhl3JWeAa4iF49LPIZu6n9K+w4jdSj8PYAh02BkoMDmYFfqmE2xVx2SZn+NLq1P4pb6dhEaYPMN+d/ZFk63iA==
  kosiskr:
    url: https://kosis.kr/openapi/Param/statisticsParameterData.do
    serviceKey: YThjNGU4OTUyNzJhM2UyMzEzYzZiNGFjNWIyOWU3OTM=